imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ViazushkiBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - '@SonataFormatter/Form/formatter.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: utf8
#        default_table_options:
#            charset: utf8
#            collate: utf8_unicode_ci
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            gedmo_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree # (optional) it will default to the name set for the mapping
                is_bundle: false

stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true
            tree: true

# Swiftmailer Configuration
swiftmailer:
    encryption: ssl
    auth_mode: login
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sonata_admin:
    templates:
        dashboard: SonataAdminBundle:Core:dashboard.html.twig
    assets:
        extra_javascripts:
#            - bundles/ivoryckeditor/ckeditor.js
            - bundles/sonataformatter/vendor/ckeditor/ckeditor.js
            - bundles/sonataformatter/vendor/markitup-markitup/markitup/jquery.markitup.js
            - assets/js/admin.js
        extra_stylesheets:
            - assets/css/admin.css
            - bundles/sonataformatter/markitup/skins/sonata/style.css

sonata_formatter:
    formatters:
        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_doctrine_orm_admin:
    # default value is null, so doctrine uses the value defined in the configuration
    entity_manager: ~

    audit:
        force: true

    templates:
        form:
            - SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig
        filter:
            - SonataDoctrineORMAdminBundle:Form:filter_admin_fields.html.twig
        types:
            list:
                array:      SonataAdminBundle:CRUD:list_array.html.twig
                boolean:    SonataAdminBundle:CRUD:list_boolean.html.twig
                date:       SonataAdminBundle:CRUD:list_date.html.twig
                time:       SonataAdminBundle:CRUD:list_time.html.twig
                datetime:   SonataAdminBundle:CRUD:list_datetime.html.twig
                text:       SonataAdminBundle:CRUD:base_list_field.html.twig
                trans:      SonataAdminBundle:CRUD:list_trans.html.twig
                string:     SonataAdminBundle:CRUD:base_list_field.html.twig
                smallint:   SonataAdminBundle:CRUD:base_list_field.html.twig
                bigint:     SonataAdminBundle:CRUD:base_list_field.html.twig
                integer:    SonataAdminBundle:CRUD:base_list_field.html.twig
                decimal:    SonataAdminBundle:CRUD:base_list_field.html.twig
                identifier: SonataAdminBundle:CRUD:base_list_field.html.twig
                currency:   SonataAdminBundle:CRUD:list_currency.html.twig
                percent:    SonataAdminBundle:CRUD:list_percent.html.twig
                choice:     SonataAdminBundle:CRUD:list_choice.html.twig
                url:        SonataAdminBundle:CRUD:list_url.html.twig

            show:
                array:      SonataAdminBundle:CRUD:show_array.html.twig
                boolean:    SonataAdminBundle:CRUD:show_boolean.html.twig
                date:       SonataAdminBundle:CRUD:show_date.html.twig
                time:       SonataAdminBundle:CRUD:show_time.html.twig
                datetime:   SonataAdminBundle:CRUD:show_datetime.html.twig
                text:       SonataAdminBundle:CRUD:base_show_field.html.twig
                trans:      SonataAdminBundle:CRUD:show_trans.html.twig
                string:     SonataAdminBundle:CRUD:base_show_field.html.twig
                smallint:   SonataAdminBundle:CRUD:base_show_field.html.twig
                bigint:     SonataAdminBundle:CRUD:base_show_field.html.twig
                integer:    SonataAdminBundle:CRUD:base_show_field.html.twig
                decimal:    SonataAdminBundle:CRUD:base_show_field.html.twig
                currency:   SonataAdminBundle:CRUD:base_currency.html.twig
                percent:    SonataAdminBundle:CRUD:base_percent.html.twig
                choice:     SonataAdminBundle:CRUD:show_choice.html.twig
                url:        SonataAdminBundle:CRUD:show_url.html.twig

knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        distinct: true
    template:
        pagination: '@ViazushkiBundle/Resources/views/pagination.html.twig'

liip_imagine:
    resolvers:
       default:
          web_path:
            web_root: '%kernel.project_dir%/web'
            cache_prefix: 'cache'

    filter_sets:
        cache: ~
        image_54_54:
            quality: 100
            filters:
                thumbnail: { size: [54, 54], mode: outbound }
        image_225_146:
            quality: 100
            filters:
                thumbnail: { size: [225, 146], mode: outbound }
        image_300_400:
            quality: 100
            filters:
                thumbnail: { size: [300, 400], mode: outbound }
        image_600_400:
            quality: 100
            filters:
                thumbnail: { size: [600, 400], mode: outbound }
        image_400_600:
            quality: 100
            filters:
                thumbnail: { size: [400, 600], mode: outbound }

fos_rest:
    body_listener: true
    view:
      view_response_listener: true
    routing_loader:
        prefix_methods: false
    serializer:
        serialize_null: true
    body_converter:
        enabled: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: true }
    zone:
        - { path: ^/api/* }

nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)
    documentation:
        info:
            title: Viazushki
            description: Viazushki REST API
            version: 1.0.0
        security_definitions:
            api_key:
                type: apiKey
                name: api_key
                in: header
        security:
            api_key: []


lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'
    token_extractors:
        authorization_header:      # look for a token as Authorization Header
            enabled: true
            prefix:  Bearer
            name:    Authorization
        query_parameter:           # check token in query string parameter
            enabled: true
            name:    bearer

white_october_breadcrumbs:
    separator:          ''
    separatorClass:     'separator'
    listId:             'breadcrumbs'
    listClass:          'breadcrumb'
    itemClass:          'breadcrumb-item'
    linkRel:            ''
    locale:             ~ # defaults to null, so the default locale is used
    translation_domain: ~ # defaults to null, so the default domain is used
    viewTemplate:       'WhiteOctoberBreadcrumbsBundle::microdata.html.twig'

viazushki:
    comments:
        edit_time: 1800
        per_page: 5
    toys:
        per_page: 6
        last_added: 5
    header:
        name: 'PoweredBy'
        value: 'Wordpress :)'
    email: 'vel202007@gmail.com'
