security:
    encoders:
        ViazushkiBundle\Entity\User: plaintext
#            algorithm: bcrypt
#            cost: 12

    providers:
        my_db_provider:
            entity:
                class:  ViazushkiBundle:User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            provider: my_db_provider
            form_login:
                login_path: viazushki_login
                check_path: viazushki_login
                target_path_parameter: viazushki_homepage
                username_parameter: login[email]
                password_parameter: login[password]
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
