security:
    encoders:
        ViazushkiBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        my_db_provider:
            entity:
                class:  ViazushkiBundle:User

    firewalls:
        dev:
            pattern: ^\/api\/((profiler|wdt|doc)|css|images|js)
            security: false
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            pattern: ^/
            anonymous: ~
            provider: my_db_provider
            switch_user: ~
            form_login:
                login_path: viazushki_login
                check_path: viazushki_login
                target_path_parameter: viazushki_homepage
                username_parameter: login[email]
                password_parameter: login[password]
                remember_me: true
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /logout
                target: /
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                #always_remember_me: true

    access_control:
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_API_USER }
        - { path: ^/admin/viazushki/user, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

    role_hierarchy:
        ROLE_ADMIN:   ROLE_USER
        ROLE_SUPER_ADMIN:     [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_API_USER]
