# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    viazushki_email: 'viazushki@viazushki.com'
    viazuski_contact_email_subject: 'Сообщение от Viazushki.com'

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
#        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
#        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]

    admin.category:
        class: ViazushkiBundle\Admin\CategoryAdmin
        arguments: [~, ViazushkiBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Content, label: Categories }
        public: true

    admin.tag:
        class: ViazushkiBundle\Admin\TagAdmin
        arguments: [~, ViazushkiBundle\Entity\Tag, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Content, label: Tags }
        public: true

    admin.toy:
        class: ViazushkiBundle\Admin\ToyAdmin
        arguments: [~, ViazushkiBundle\Entity\Toy, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Content, label: Toys }
        public: true

    admin.image:
        class: ViazushkiBundle\Admin\ImageAdmin
        arguments: [~, ViazushkiBundle\Entity\Image, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Content, label: Images }
        public: true

    admin.user:
        class: ViazushkiBundle\Admin\UserAdmin
        arguments: [~, ViazushkiBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Settings, label: Users }
        public: true
