viazushki_swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

viazushki_homepage:
    path: /{_locale}
    defaults: { _controller: ViazushkiBundle:Default:index, _locale: 'ru' }
    requirements:
        _locale: en|ru

viazushki_login:
    path: /{_locale}/login
    defaults: { _controller: ViazushkiBundle:Security:login }
    requirements:
        _locale: en|ru

viazushki_register:
    path: /{_locale}/register
    defaults: { _controller: ViazushkiBundle:Security:register }
    requirements:
        _locale: en|ru

viazushki_search_toy:
    path: /{_locale}/search
    defaults: { _controller: ViazushkiBundle:Default:search, _locale: 'ru' }
    requirements:
        _locale: en|ru

viazushki_contacts:
    path: /{_locale}/contacts
    defaults: { _controller: ViazushkiBundle:Contact:contact }
    requirements:
        _locale: en|ru

viazushki_subscribe:
    path: /{_locale}/subscribe
    defaults: { _controller: ViazushkiBundle:Subscribe:subscribe }
    requirements:
        _locale: en|ru

viazushki_toy_by_tag:
    path: /{_locale}/tag/{slug}
    defaults: { _controller: ViazushkiBundle:Default:toyByTag, slug: ''}
    requirements:
        _locale: en|ru

viazushki_toy_by_category:
    path: /{_locale}/category/{slug}
    defaults: { _controller: ViazushkiBundle:Default:toyByCategory, slug: ''}
    requirements:
        _locale: en|ru

viazushki_toy:
    path: /{_locale}/{slug}
    defaults: { _controller: ViazushkiBundle:Default:showToy }
    requirements:
        _locale: en|ru

viazushki_comment_add:
    path: /comment/add/{toy}
    defaults: { _controller: ViazushkiBundle:Comment:add }

viazushki_comment_addChild:
    path: /comment/add_child/{toy}/{commentParent}
    defaults: { _controller: ViazushkiBundle:Comment:addChild }

viazushki_comment_edit:
    path: /comment/edit/{comment}
    defaults: { _controller: ViazushkiBundle:Comment:edit }

viazushki_comment_delete:
    path: /comment/delete/{comment}
    defaults: { _controller: ViazushkiBundle:Comment:delete }

viazushki_like_update:
    path: /like/update/{slug}
    defaults: { _controller: ViazushkiBundle:Like:update }
