viazushki_homepage:
    path:     /
    defaults: { _controller: ViazushkiBundle:Default:index }

viazushki_contacts:
    path:     /contacts
    defaults: { _controller: ViazushkiBundle:Contact:contact }

viazushki_toy_by_tag:
    path:     /tag/{tagId}
    defaults: { _controller: ViazushkiBundle:Default:index, tagId: ''}
    requirements:
        tagId:  '\d+'

viazushki_toy_by_category:
    path:     /category/{categoryId}
    defaults: { _controller: ViazushkiBundle:Default:index, categoryId: ''}
    requirements:
        tagId:  '\d+'
