viazushki_homepage:
    path:     /
    defaults: { _controller: ViazushkiBundle:Default:index }

viazushki_contacts:
    path:     /contacts
    defaults: { _controller: ViazushkiBundle:Contact:contact }

viazushki_toy_by_tag:
    path:     /tag/{slug}
    defaults: { _controller: ViazushkiBundle:Default:toyByTag, slug: ''}

viazushki_toy_by_category:
    path:     /category/{slug}
    defaults: { _controller: ViazushkiBundle:Default:toyByCategory, slug: ''}

viazushki_login:
    path: /login
    defaults: { _controller: ViazushkiBundle:Security:login }
