services:
#    viazushki.example:
#        class: ViazushkiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    viazushki.sending_message:
        class: ViazushkiBundle\Service\SendingMessage
        arguments:
            $viazushkiEmail: '%viazushki_email%'
            $viazuskiContactEmailSubject: '%viazuski_contact_email_subject%'
            $mailer: '@mailer'

    viazushki.viazushki_extension:
        class: ViazushkiBundle\Twig\ViazushkiExtenson
        tags: [twig.extension]

    viazushki.comment_voter:
        class: ViazushkiBundle\Security\CommentVoter
        arguments:
            $decisionManager: '@security.access.decision_manager'
            $commentEditTime: '%comment_edit_time%'
        tags: [security.voter]

    viazushki.menu_builder:
        class: ViazushkiBundle\Menu\MenuBuilder
        arguments: ['@knp_menu.factory']
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }

    viazushki.file_uploader:
        class: ViazushkiBundle\Service\FileUploader
        arguments:
            $targetDir: '%kernel.root_dir%/../web/assets/images'

    viazushki.file_upload_listener:
        class: ViazushkiBundle\Listeners\FileUploadListener
        arguments:
            $uploader: '@viazushki.file_uploader'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }
        public: true
