services:

    viazushki.send_email:
        class: ViazushkiBundle\Emails\SendEmail
        arguments:
            $mailer: '@mailer'
        public: false

    viazushki.viazushki_extension:
        class: ViazushkiBundle\Twig\ViazushkiExtension
        tags: [twig.extension]

    viazushki.comment_voter:
        class: ViazushkiBundle\Security\CommentVoter
        arguments:
            $decisionManager: '@security.access.decision_manager'
            $commentEditTime: '%viazushki.comments_edit_time%'
        tags: [security.voter]

    viazushki.menu_builder:
        class: ViazushkiBundle\Menu\MenuBuilder
        arguments: ['@knp_menu.factory']
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }

    viazushki.file_uploader:
        class: ViazushkiBundle\Files\FileUploader
        arguments:
            $targetDir: '%kernel.root_dir%/../web/assets/images'

    viazushki.image_upload_listener:
        class: ViazushkiBundle\Listeners\ImageUploadListener
        arguments:
            $uploader: '@viazushki.file_uploader'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }
        public: true

    viazushki.response_listener:
        class: ViazushkiBundle\Listeners\AddHeaderListener
        tags:
            - { name: kernel.event_listener, event: kernel.response }
        arguments: [ '%viazushki.header_name%', '%viazushki.header_value%' ]

    viazushki.send_contact_email:
        class: ViazushkiBundle\Emails\SendContactEmail
        arguments:
            $templating: '@Twig_Environment'
            $sendEmail: '@viazushki.send_email'
            $viazushkiEmail: '%viazushki.email%'

    viazushki.send_subscribe_email:
        class: ViazushkiBundle\Emails\SendSubscribeEmail
        arguments:
            $templating: '@Twig_Environment'
            $sendEmail: '@viazushki.send_email'
            $viazushkiEmail: '%viazushki.email%'

    viazushki.send_news_email:
        class: ViazushkiBundle\Emails\SendNewsEmail
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $templating: '@Twig_Environment'
            $sendEmail: '@viazushki.send_email'
            $viazushkiEmail: '%viazushki.email%'

    ViazushkiBundle\Command\SendNewsEmailCommand:
        tags:
            - { name: 'console.command', command: 'viazushki:email:send-news' }
        arguments: [ '@viazushki.send_news_email' ]
